name: CI
on: 
    push: 
        branches:
            - main

jobs:
    flutter-analyze:
        name: Run analyze
        runs-on: ubuntu-latest
        steps:
            - name: getting project
              uses: actions/checkout@v3

            - name: getting flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.13.6'
                channel: 'stable'

            - run: flutter pub get

            - run: flutter analyze

    build-web:
        name: build and publish webapp
        runs-on: ubuntu-latest
        needs: [flutter-analyze]
        steps: 
            - run: ls
            
            - name: getting project
              uses: actions/checkout@v3
            
            - name: getting flutter
              uses: subosito/flutter-action@v2

            - name: getting dependencies - pub get
              run: flutter pub get

            - name: building web app
              run: flutter build web --release
            
            - name: Deploying Netlify
              uses: nwtgck/actions-netlify@v2.0
              with:
                publish-dir: './build/web'
                production-branch: main
                github-token: ${{secrets.GITHUB_TOKEN}}
                deploy-message: 'Deploy from GitHub Actions'
                enable-pull-request-comment: false
                enable-commit-comment: true
                overwrites-pull-request-comment: true
              env:
                NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
                NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}