name: CI
on: 
    push: 
        branches:
            - main

jobs:
    flutter-analyze:
        name: Run analyze
        runs-on: ubuntu-latest
        steps:
            - name: getting project
              uses: actions/checkout@v3
            - name: getting flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.13.6'
                channel: 'stable'
            - run: flutter --version
            - run: flutter pub get
            - run: flutter analyze


