name: my-flow
on:
    push:
        branches: 
            - main

jobs:
    nombre-trabajo:
        name: my job
        runs-on: ubuntu-latest
        steps:
            - run: echo "hola mundo"



